export const actionTypes = {
  API_TEST_REQUEST: 'API_TEST_REQUEST',
  API_TEST_SUCCESS: 'API_TEST_SUCCESS',
  API_TEST_FAILURE: 'API_TEST_FAILURE',
  CREATE_NOTE_REQUEST: 'CREATE_NOTE_REQUEST',
  CREATE_NOTE_SUCCESS: 'CREATE_NOTE_SUCCESS',
  CREATE_NOTE_FAILURE: 'CREATE_NOTE_FAILURE'
}
